# baseURL = "http://example.org/"
baseURL = "https://maricaya.github.io/"
languageCode = "zh-Hans"
title = "Mariacaya"
# theme = "ananke"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2019
    author = "cxl"                           # Author's name
    avatar = "/images/me/avatar.jpg"           # Author's avatar
    subtitle = "stay hungry,stay foolish"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "Maricaya"
    # Twitter = "xxoo"
    Email   = "915270549@qq.com"
    # Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Facebook = "xxoo"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

